#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Builds words.js: the five free levels of the app's word lists, for the web.

Usage:  python make-words.py          (needs ../SYVT checked out beside this)

The app generates lib/game/words.dart from the same JSON, so the site and the
Android game teach the same words in the same order. Only levels 1 to 5 come
across: those are the levels the free version plays, and the web version is
the free version.

Each entry is [correct, ...misspellings]; the game picks one misspelling at
random when it decides to show a wrong word.
"""
import io
import json
import os

SRC = os.path.join('..', 'SYVT', 'tool', 'words')
OUT = 'words.js'
LANGS = ('en', 'de', 'fr')
FREE_LEVELS = 5


def load(lang):
    with io.open(os.path.join(SRC, '%s.json' % lang), encoding='utf-8') as f:
        data = json.load(f)
    levels = []
    for level in data['levels'][:FREE_LEVELS]:
        entries = []
        for w in level['words']:
            wrongs = [x for x in w['w'] if x and x != w['r']]
            if not wrongs:
                raise SystemExit('%s level %d: %r has no misspelling'
                                 % (lang, level['level'], w['r']))
            entries.append([w['r']] + wrongs)
        levels.append(entries)
    return levels


def main():
    out = io.StringIO()
    out.write('// GENERATED by make-words.py from ../SYVT/tool/words/*.json.\n')
    out.write('// The five free levels, the same words the Android game\n')
    out.write('// teaches. Each entry is [correct, ...misspellings].\n')
    out.write('window.SYVT_WORDS = {\n')
    for lang in LANGS:
        levels = load(lang)
        out.write('  %s: [\n' % lang)
        for i, entries in enumerate(levels):
            out.write('    [ // level %d\n' % (i + 1))
            for e in entries:
                out.write('      %s,\n' % json.dumps(e, ensure_ascii=False))
            out.write('    ],\n')
        out.write('  ],\n')
        print('%s  %d levels, %d words'
              % (lang, len(levels), sum(len(x) for x in levels)))
    out.write('};\n')
    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(out.getvalue())
    print('%s  %.1f KB' % (OUT, len(out.getvalue()) / 1024))


if __name__ == '__main__':
    main()
