#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Builds words.js: the five free levels of the app's word lists, for the web.

Usage:  python make-words.py          (needs ../SYVT checked out beside this)

The app generates lib/game/words.dart from the same JSON, so the site and the
Android game teach the same words in the same order. Only levels 1 to 5 come
across: those are the levels the free version plays, and the web version is
the free version.

Each entry is [correct, ...misspellings]; the game picks one misspelling at
random when it decides to show a wrong word.

It also writes SYVT_VOICE: the id of the spoken clip for every word the page
can ever read out loud, which is levels 1 and 2 (see below). The ids are
computed HERE, by importing the app's own tool/tts/speech_key.py, rather than
hashed in the browser. A third implementation of the normaliser and the hash
would be a third chance to drift from the other two -- and a drifted hash
does not throw, it just misses every file, and the voice goes quiet with no
error anywhere. This way the page never hashes anything: it looks a word up.

For German the id is Germany's spelling, from ../SYVT/tool/words/de_germany.json,
for the fourteen words the two countries spell differently -- the same
`WordEntry.spoken` rule the app follows. The map is keyed by the SWISS form,
because that is what words.js carries and what the tile shows.
"""
import io
import json
import os
import sys

SRC = os.path.join('..', 'SYVT', 'tool', 'words')
TTS = os.path.join('..', 'SYVT', 'tool', 'tts')
OUT = 'words.js'
LANGS = ('en', 'de', 'fr')
FREE_LEVELS = 5

# The levels the page reads aloud. Two, as in the app (Limits.freeVoiceMaxLevel),
# and the pool at level 2 reaches no further back than level 1, so these two
# levels are exactly the words that can ever be spoken here.
VOICE_LEVELS = 2

sys.path.insert(0, os.path.abspath(TTS))
from speech_key import speech_key, voice_id  # noqa: E402


def germany_of(lang):
    """{Swiss right form -> Germany's right form}, empty where there is none."""
    path = os.path.join(SRC, '%s_germany.json' % lang)
    if not os.path.exists(path):
        return {}
    with io.open(path, encoding='utf-8') as f:
        data = json.load(f)
    return dict((w['swiss'], w['r']) for w in data['words'])


def load(lang):
    with io.open(os.path.join(SRC, '%s.json' % lang), encoding='utf-8') as f:
        data = json.load(f)
    levels = []
    for level in data['levels'][:FREE_LEVELS]:
        entries = []
        for w in level['words']:
            wrongs = [x for x in w['w'] if x and x != w['r']]
            if not wrongs:
                raise SystemExit('%s level %d: %r has no misspelling'
                                 % (lang, level['level'], w['r']))
            entries.append([w['r']] + wrongs)
        levels.append(entries)
    return levels


def voices(lang, levels):
    """{right form -> clip id} for the levels the page reads out loud."""
    germany = germany_of(lang)
    out = {}
    for entries in levels[:VOICE_LEVELS]:
        for e in entries:
            right = e[0]
            key = speech_key(germany.get(right, right))
            if key is None:
                raise SystemExit('%s: %r has nothing sayable' % (lang, right))
            out[right] = voice_id(lang, key)
    return out


def main():
    out = io.StringIO()
    out.write('// GENERATED by make-words.py from ../SYVT/tool/words/*.json.\n')
    out.write('// The five free levels, the same words the Android game\n')
    out.write('// teaches. Each entry is [correct, ...misspellings].\n')
    out.write('window.SYVT_WORDS = {\n')
    spoken = {}
    for lang in LANGS:
        levels = load(lang)
        spoken[lang] = voices(lang, levels)
        out.write('  %s: [\n' % lang)
        for i, entries in enumerate(levels):
            out.write('    [ // level %d\n' % (i + 1))
            for e in entries:
                out.write('      %s,\n' % json.dumps(e, ensure_ascii=False))
            out.write('    ],\n')
        out.write('  ],\n')
        print('%s  %d levels, %d words, %d spoken'
              % (lang, len(levels), sum(len(x) for x in levels),
                 len(spoken[lang])))
    out.write('};\n')

    out.write('\n')
    out.write('// The clip id of every word the page can read out loud: the\n')
    out.write('// first %d levels, which is as far as the free voice goes.\n'
              % VOICE_LEVELS)
    out.write('// Keyed by the spelling the tile shows; for German the id is\n')
    out.write("// Germany's spelling, which is the one the voice can read.\n")
    out.write('window.SYVT_CLIPS = {\n')
    for lang in LANGS:
        out.write('  %s: {\n' % lang)
        for right, vid in spoken[lang].items():
            out.write('    %s: "%s",\n'
                      % (json.dumps(right, ensure_ascii=False), vid))
        out.write('  },\n')
    out.write('};\n')

    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(out.getvalue())
    print('%s  %.1f KB' % (OUT, len(out.getvalue()) / 1024))


if __name__ == '__main__':
    main()
